plugins {
    id 'base'
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    group = 'net.ingoh.myagents'
    version = "$version"

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

tasks.register("cleanAll") {
    group = 'build'
    description = 'Cleans all projects'
    subprojects.forEach { project ->
        dependsOn(project.tasks.named("clean"))
    }
}

tasks.register("buildAll") {
    group = 'build'
    description = 'Builds all projects'
    subprojects.forEach { project ->
        dependsOn(project.tasks.named("build"))
    }
}

tasks.register("generateGrammarSource") {
    group = 'build'
    description = 'Generates the grammar files'
    dependsOn(':myagents-core:generateGrammarSource')
}

tasks.register("jarServer") {
    dependsOn ':lsp-server:shadowJar'
    group = 'build'
    description = 'Builds the server jar'
}