var origFuncs = {};

window.onload = initializeDebugCodeGenerator();

// Initializes the debug code generator to write the code generated by the blocks in the workspace
function initializeDebugCodeGenerator() {
    try {
        var toolbox = document.getElementById('toolbox');
        var blocks = toolbox.getElementsByTagName('block');
        for (var i = 0; i < blocks.length; i++) {
            var func = Blockly.Java[blocks[i].getAttribute('type')];
            origFuncs[blocks[i].getAttribute('type')] = func;
            if (typeof func === 'function') {
                Blockly.Java[blocks[i].getAttribute('type')] = withDebugCode();
            }
        }
    } catch (e) {
        // ignore
    }
}

// Creates and displays the code that is generated from each block in the specified workspace and combines it
function workspaceToCodeDebug(workspace) {
    if (!workspace) {
        // Backwards compatibility from before there could be multiple workspaces.
        console.warn(
            'No workspace specified in workspaceToCode call.  Guessing.');
        workspace = common.getMainWorkspace();
    }
    // Just output the XML of the workspace.
    let code = Blockly.Xml.workspaceToDom(workspace);
    let codeStr = xmlToString(code);
    document.getElementById("debugText1").innerHTML = codeStr;
    return codeStr;
}

// Returns the color of each block in the workspace
function getColor(workspace, block) {
    var blocks = workspace.getAllBlocks();
    for (var i = 0; i < blocks.length; i++) {
        if (blocks[i].type === block) {
            return blocks[i].getColour();
        }
    }
    return "#000000";
}

// Brightens an element such as a background or breakpoint
function brighter(color, multiplier) {
    var r = parseInt(color.substring(1, 3), 16);
    var g = parseInt(color.substring(3, 5), 16);
    var b = parseInt(color.substring(5, 7), 16);
    r = Math.round(r * multiplier);
    g = Math.round(g * multiplier);
    b = Math.round(b * multiplier);
    if (r > 255) r = 255;
    if (g > 255) g = 255;
    if (b > 255) b = 255;
    var rr = r.toString(16);
    var gg = g.toString(16);
    var bb = b.toString(16);
    if (rr.length === 1) rr = "0" + rr;
    if (gg.length === 1) gg = "0" + gg;
    if (bb.length === 1) bb = "0" + bb;
    return "#" + rr + gg + bb;
}

function xmlToString(xml) {
    let str = null;
    if (typeof xml === 'string') {
        str = xml;
    }
    else if (xml instanceof XMLDocument) {
        str = xml.documentElement.outerHTML;
    }
    else if (xml instanceof Element) {
        str = xml.outerHTML;
    }
    else if (xml instanceof Node) {
        str = xml.textContent;
    }
    else {
        throw new Error('Cannot convert XML to string: ' + xml);
    }
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}