plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

version = '' // No version so the jar has no version suffix

application {
    mainClass = 'net.ingoh.myagents.lsp.server.Main'
}

dependencies {
    implementation project(":myagents-core")
    implementation "org.antlr:antlr4-runtime:$antlrVersion"
    implementation "org.eclipse.lsp4j:org.eclipse.lsp4j:$lsp4jVersion"
}

shadowJar {
    archiveClassifier.set('')
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}